packages:
  - 'saas-api/**'
  - 'saas-mobile'
  - 'saas-web'

allowBuilds:
  '@uni-helper/unocss-preset-uni': true
  core-js: true
  core-js-pure: true
  esbuild: true
  tesseract.js: true
  vue-demi: true

overrides:
  unconfig: '7.3.2'
  '@intlify/message-compiler': '9.14.5'
  '@intlify/core-base': '9.14.5'
  # 移动端兼容
  vue: '3.4.21'
  '@vue/runtime-core': '3.4.21'
  vite: '5.2.8'
