ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'PENDING_RISK_PRE';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'RISK_PRE_PASSED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'RISK_PRE_REJECTED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'PENDING_FUNDER_PRE';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'FUNDER_PRE_PASSED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'FUNDER_PRE_REJECTED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SIGNING_PROGRESS';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'PENDING_LOAN_REQUEST';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'LOAN_REQUEST_REVIEWING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'LOAN_REQUEST_APPROVED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'LOAN_REQUEST_REJECTED';

