ALTER TABLE "Application"
ADD COLUMN IF NOT EXISTS "businessType" TEXT NOT NULL DEFAULT 'CAR_LOAN',
ADD COLUMN IF NOT EXISTS "currentNode" INTEGER NOT NULL DEFAULT 1100,
ADD COLUMN IF NOT EXISTS "currentStatus" INTEGER NOT NULL DEFAULT 10;

UPDATE "Application"
SET
  "businessType" = COALESCE("businessType", 'CAR_LOAN'),
  "currentNode" = CASE "status"
    WHEN 'DRAFT' THEN 1100
    WHEN 'SUBMITTED' THEN 2000
    WHEN 'PENDING_FIRST_REVIEW' THEN 5000
    WHEN 'FIRST_REVIEW_PASSED' THEN 6000
    WHEN 'PENDING_FINAL_REVIEW' THEN 6000
    WHEN 'FINAL_REVIEW_PASSED' THEN 7000
    WHEN 'PENDING_FUNDER_REVIEW' THEN 8000
    WHEN 'FUNDER_REVIEW_PASSED' THEN 7000
    WHEN 'PENDING_SIGN' THEN 1400
    WHEN 'SIGNED' THEN 7000
    WHEN 'PENDING_DISBURSEMENT' THEN 7000
    WHEN 'DISBURSED' THEN 9000
    WHEN 'PENDING_SUPPLEMENT' THEN 4000
    ELSE "currentNode"
  END,
  "currentStatus" = CASE
    WHEN "status" IN (
      'FIRST_REVIEW_REJECTED',
      'FINAL_REVIEW_REJECTED',
      'FUNDER_REVIEW_REJECTED',
      'CANCELLED'
    ) THEN 30
    WHEN "status" = 'PENDING_SUPPLEMENT' THEN 50
    WHEN "status" = 'DISBURSED' THEN 90
    ELSE 10
  END;

CREATE INDEX IF NOT EXISTS "Application_businessType_idx" ON "Application"("businessType");
CREATE INDEX IF NOT EXISTS "Application_currentNode_idx" ON "Application"("currentNode");
CREATE INDEX IF NOT EXISTS "Application_currentStatus_idx" ON "Application"("currentStatus");
