ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "nation" TEXT,
ADD COLUMN IF NOT EXISTS "householdAddress" TEXT,
ADD COLUMN IF NOT EXISTS "issuingAuthority" TEXT,
ADD COLUMN IF NOT EXISTS "idCardValidFrom" TEXT,
ADD COLUMN IF NOT EXISTS "idCardValidTo" TEXT,
ADD COLUMN IF NOT EXISTS "idCardFront" TEXT,
ADD COLUMN IF NOT EXISTS "idCardBack" TEXT;

ALTER TABLE "Vehicle"
ADD COLUMN IF NOT EXISTS "ownerName" TEXT,
ADD COLUMN IF NOT EXISTS "address" TEXT,
ADD COLUMN IF NOT EXISTS "usageNature" TEXT,
ADD COLUMN IF NOT EXISTS "sealInfo" TEXT,
ADD COLUMN IF NOT EXISTS "engineNumber" TEXT,
ADD COLUMN IF NOT EXISTS "registerDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "vehicleImgUrl" TEXT;
