import uniHelper from '@uni-helper/eslint-config'

export default uniHelper({}, {
  rules: {
    'vue/block-order': 'off',
    'vue/html-indent': 'off',
    'vue/html-self-closing': 'off',
    'vue/multiline-html-element-content-newline': 'off',
    'vue/singleline-html-element-content-newline': 'off',
    'style/indent': 'off',
    'style/quotes': 'off',
    'style/semi': 'off',
    'style/arrow-parens': 'off',
    'style/brace-style': 'off',
    'style/member-delimiter-style': 'off',
    'style/operator-linebreak': 'off',
    'vue/operator-linebreak': 'off',
    'style/comma-dangle': 'off',
    'antfu/if-newline': 'off',
    'antfu/top-level-function': 'off',
    'vue/attribute-hyphenation': 'off',
    'vue/first-attribute-linebreak': 'off',
    'vue/html-tag-newline': 'off',
    'vue/html-closing-tag-newline': 'off',
    'vue/max-attributes-per-line': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'perfectionist/sort-exports': 'off',
    'perfectionist/sort-named-exports': 'off',
    'perfectionist/sort-objects': 'off',
    'perfectionist/sort-union-types': 'off',
    'jsonc/sort-keys': 'off',
    'no-console': 'warn',
  },
})
